### ISSUE TITLE
USER STORY: Manage DIY Projects Categories

### ISSUE THREAD

**Issue by Juanma1313** [Juanma1313/diyshop#18]
As **Administrator**, I can **create/modify/delete categories to classify the DIY Projects in the database**, so that **users can filtrate DIY Projects by the categories of their interest**

###### Acceptance Criteria

- Acceptance Criteria 1
  **Given** that I am a `Administrator`
  **When** I want a new Category to classify DIY Projects
  **Then** I can use the admin interface to add it to the list of Categories.

- Acceptance Criteria 2
  **Given** that I am a `Administrator`
  **When** I create a new Category
  **Then** I assign an internal lowercase name to be used by the application, and a friendly name that will be shown in the webpage.

- Acceptance Criteria 3
  **Given** that I am a `Administrator`
  **When** I need to modify a Category
  **Then** I can use the admin interface to edit the internal and the friendly name.

- Acceptance Criteria 4
  **Given** that I am a `Administrator`
  **When** I need to delete a Category
  **Then** I can use the admin interface to delete the selected Category

- Acceptance Criteria 5
  **Given** that I am a `Administrator`
  **When** I have deleted a Category
  **Then** The DIY Projects that had that Category, stays without Category.

###### Tasks

- [X] Task 1 – Create product.Category class model that will be used to instantiate each Category object
- [X] Task 2 – Modify the DIY Project object model 'Thing' to include the Category model 
- [X] Task 3 – Create the admin.CategoryAdmin view to handle Category elements in the Admin user interface.
