### ISSUE TITLE
USER STORY: Create Development Environment

### ISSUE THREAD

**Issue by Juanma1313** [Juanma1313/diyshop#2]
As **developer**, I can **setup the development environment**,
so that **I can start developing the website**

###### Tasks

- [X] Task 1 – Install Visual Studio Code in local environment
- [X] Task 2 – Create website Github repository and start remote  environment
- [X] Task 3 – Install Django and all required libraries for runtime and development of the website
- [X] Task 4 – Create Django project and application
- [X] Task 5 - Create local database structures in SQLite3
- [X] Task 6 - Create fixtures from deployed DIY Site database and media storage
- [X] Task 7 - Upload fixtures to new database
