### ISSUE TITLE
USER STORY: Sorting DIY Projects

### ISSUE THREAD

**Issue by Juanma1313** [Juanma1313/diyshop#20]
As **user**, I can **use a predefined sorting option from the main-nav bar**, so that **I can view the list of DIY Projects in a particular order**

###### Acceptance Criteria

- Acceptance Criteria 1
  **Given** that I am a `user`
  **When** I want to sort DIY Projects by date
  **Then** I can use the main navigation menu to select the new arrival to get the DIY Project list ordered from newer to older.
  **Then** I can use the dropdown sorting menu to select the Date(new to old) or Date (old to new) to get the DIY Project list ordered as selected

- Acceptance Criteria 2
  **Given** that I am a `user`
  **When** I want to sort DIY Projects by price
  **Then** I can use the main navigation menu to select the `By Price` option to get the DIY Project list ordered by price from lower to higher.
  **Then** I can use the dropdown sorting menu to select the Price(low to high) or Price(high to low) to get the DIY Project list ordered as selected

- Acceptance Criteria 3
  **Given** that I am a `user`
  **When** I want to sort DIY Projects by rating
  **Then** I can use the main navigation menu to select the `By Rating` option to get the DIY Project list ordered by rating  from higher to lower.
  **Then** I can use the dropdown sorting menu to select the Rating(low to high) or Rating(high to low) to get the DIY Project list ordered as selected

- Acceptance Criteria 4
  **Given** that I am a `user`
  **When** I want to sort DIY Projects by Category
  **Then** I can use the main navigation menu to select the `By Category` option to get the DIY Project list ordered by category from A to Z.
  **Then** I can use the dropdown sorting menu to select the Category(A to Z) or Category(Z to A) to get the DIY Project list ordered as selected

- Acceptance Criteria 5
  **Given** that I am a `user`
  **When** I want to sort DIY Projects by name
  **Then** I can use the dropdown sorting menu to select the Name(A to Z) or Name(Z to A) to get the DIY Project list ordered as selected

###### Tasks

- [X] Task 1 – Modify the main-nav template to displays the list of useful ordering options
- [X] Task 2 – Modify the products template include a dropdown list of the required ordering options
- [X] Task 3 – Modify the products/views.all_products view tu include the selected ordering to the database query for the DIY Projects list.
