### ISSUE TITLE
USER STORY: add Projects to the shopping cart

### ISSUE THREAD

**Issue by Juanma1313** [Juanma1313/diyshop#23]
As **User**, I can **add a Non Free DIY Proyect to my cart**, so that **I can keep track of my selections and my costs**

###### Acceptance Criteria

- Acceptance Criteria 1
  **Given** that I am a `User`
  **When** I am in a DIY project details page of a non free DIY Project
  **Then** I can use the `+` or `-` buttons to adjust the number of kits I want to add to my shopping cart (Shopping Bag).
  **Then** I can use the `Add To Bag` button to add the selected numberof DIY project kits to my shopping cart (Shopping Bag)..

###### Tasks

- [X] Task 1 – Create the bag application
- [X] Task 2 – Create the session store mecanism to hold the shopping items added
- [X] Task 3 – Create the bag/views.add_to_bag view to allow for the shopping items to be added 
- [X] Task 4 – modify the base template to include the shopping cart icon
