### ISSUE TITLE
USER STORY: initiate checkout of the shopping cart

### ISSUE THREAD

**Issue by Juanma1313** [Juanma1313/diyshop#27]
As **User**, I can **start the checkout process for the content of my sopping cart**, so that **I can show the order summary and the payment methods**

###### Acceptance Criteria

- Acceptance Criteria 1

  **Given** that I am a `User`
  **When** in the shopping cart detail page (Shopping Bag), I press the `Secure Checkout` button
  **Then** I am redirected to the checkout page, where the order form and order summary are presented.

###### Tasks

- [X] Task 1 – Create the checkout application
- [X] Task 2 – Create the checkout/models.Order class to instantiate order object
- [X] Task 3 – Create the checkout/forms.OrderForm form to handle all the required order fields
- [X] Task 4 – Create the checkout/views.checkout view to populate the order object from the shopping cart and start the payment transaction.
- [X] Task 5 – Create the checkout template to display the order form to the user
