### ISSUE TITLE
USER STORY: submit the checkout order to the online payment service

### ISSUE THREAD

**Issue by Juanma1313** [Juanma1313/diyshop#29]
As  **User**, I can **send the completed purchase form**, so that **the payment of the purchase order can be fulfilled**

###### Acceptance Criteria

- Acceptance Criteria 1

  **Given** that I am a `User`
  **When** in the checkout page with a valid checkout form, I press the `Complete Order` button 
  **Then** the order is submitted for payment to the external payment gateway.

- Acceptance Criteria 2

  **Given** that, an order has been submitted for payment to the external payment gateway.
  **When** the transaction is accepted
  **Then** The new purchase order is finally committed to the database
  **Then** An e-mail with the confirmation of the purchase is sent to the address that the user filled in the purchase form.  
  **Then** The shopping cart is cleaned of all shopping items
  **Then** the user is redirected to the checkout_success page where all the details of the purchase order is displayed

###### Tasks

- [X] Task 1 – Create the checkout/views.checkout_success view to delete the shopping cart from the user session and render the chekout_success page.
- [X] Task 2 – Create the checkout_success template to display the relevant Order information.
- [X] Task 3 – Create the confirmation_emails templates for the e-mail subject and the e-mail body.
- [X] Task 4 – Create the checkout/emails.send_confirmation_email function to create the e-mail and send it to the address in the order.
