### ISSUE TITLE
USER STORY: Administrate users

### ISSUE THREAD

**Issue by Juanma1313** [Juanma1313/diyshop#3]
As **Administrator**, I can **Create/modify/delete user accounts and their privileges**, so that **I can assign who signs in on the website and who can create or modify content**

###### Acceptance Criteria

- Acceptance Criteria 1
**Given** that I am an `Administrator` user
**When** I am in any website page
**Then** I can access the admin web page selecting the `Admin` option in the user menu

- Acceptance Criteria 2
**Given** that I am an `Administrator` user
**When** I am in admin website page
**Then** I can add/delete/modify any user

- Acceptance Criteria 3
**Given** that I am an `Administrator` user
**When** I am in admin website page
**Then** I can add/delete/modify any privilege of any user and any group

###### Tasks

- [X] Task 1 - Install and setup Django's allauth and its accounts and interfaces, extensions.
- [X] Task 2 - Create at least one administrator account
- [X] Task 3 - Customize allauth templates to the website base template
- [X] Task 4 - Create `Content Creators` user group with necessary  privileges for content creators
