### ISSUE TITLE
USER STORY: Create a user profile

### ISSUE THREAD

**Issue by Juanma1313** [Juanma1313/diyshop#31]
As **Registered User**, I can **save my billing information under my account**, so that **I can review, change and reuse it for future checkouts**

###### Acceptance Criteria

- Acceptance Criteria 1

  **Given** that I am a `User`
  **When** I sign up to the website 
  **Then** An empty profile is created.

- Acceptance Criteria 2

  **Given** that I am a `Registered User`
  **When** loading the checkout page
  **Then** the billing information (telephone, delivery address) is automatically filled in from my user profile
  **Then** a check button `save the delivery information to my profile` is checked by default

- Acceptance Criteria 3

  **Given** that I am a `Registered User`
  **When** in the checkout page
  **Then** I can change 
  **Then** I have the option toggle the check button `save the delivery information to my profile`

- Acceptance Criteria 4

  **Given** that I am a `Registered User`
  **Given** that from the checkout page, I have successfully submitted a purchase order
  **When** the check button `save the delivery information to my profile` is checked
  **Then** The delivery information from the purchase order (telephone and address) is saved to my user profile

###### Tasks

- [X] Task 1 – Create the profiles application
- [X] Task 2 – Create the profiles.UserProfile class to instantiate user profile objects in a one-to-one relation with the User class
- [X] Task 3 – Create the profiles/views.profile view to access the database user profile
- [X] Task 4 – Update checkout/views.checkout view to read user profile information and feed it to new checkouts
- [X] Task 5 – Update checkout/models.Order class to include a user profile member
