### ISSUE TITLE
USER STORY: View and Manage Profile

### ISSUE THREAD

**Issue by Juanma1313** [Juanma1313/diyshop#32]
As **Registered User**, I can **view and change my profile information under my account**, so that **I can adapt the information to future checkouts**

###### Acceptance Criteria

- Acceptance Criteria 1

  **Given** that I am a `Registered User`
  **When** I am in my user profile page
  **Then** I can view and change the delivery information
  **Then** I can view all my previous successfully submitted orders

- Acceptance Criteria 2

  **Given** that I am a `Registered User`
  **When** in my user profile page, I press the `Update InFormation` button
  **Then** The information shown in the `my profile` form is updated in the database

###### Tasks

- [X] Task 1 – Create the profiles/views.order_history to access to all the user orders
- [X] Task 2 – Create the profile/forms.UserProfileForm to accommodate the profile data into a template
- [X] Task 3 – Create the profile template to present the user profile as a web page
