### ISSUE TITLE
USER STORY: User Messages and Notifications

### ISSUE THREAD

**Issue by Juanma1313** [Juanma1313/diyshop#34]
As a **User**, I can **be informed about results of my operations**, so that **I get confirmations, information, warnings and errors about my interaction with the website**.

###### Acceptance Criteria

- Acceptance Criteria 1

  **Given** that I am a `User`
  **When** I request sign up, sign in or sign out
  **Then** I receive a pop-up message that notifies me of the result of the request

- Acceptance Criteria 2

  **Given** that I am a `Registered User`
  **When** I request to modify my email or password
  **Then** I receive a pop-up message that notifies me of the result of the request

- Acceptance Criteria 3

  **Given** that I am a `User`
  **When** I request DIY Project ordering, filtering or searching
  **Then** I receive a pop-up message whenever there is an error in the request

- Acceptance Criteria 4

  **Given** that I am a `Registered User`
  **When** I create, edit or delete a DIY Project
  **Then** I receive a pop-up message with the result of the operation

- Acceptance Criteria 5

  **Given** that I am a `User`
  **When** I modify my shopping cart, adding or deleting products 
  **Then** I receive a pop-up message with the result of the operation

- Acceptance Criteria 6

  **Given** that I am a `User`
  **When** I receive a pop-up message with a success result of a shopping cart operation
  **Then** the pop-up message contains a summary of my shopping cart
  **Then** the pop-up provides the button `Go To Secure Cheakout` to directly go to the checkout page.

- Acceptance Criteria 7

  **Given** that I am a `User`
  **When** I request a checkout 
  **Then** I receive a pop-up message that notifies me of the result of the request

- Acceptance Criteria 8

  **Given** that I am a `User`
  **When** I modify my profile
  **Then** I receive a pop-up message with the result of the operation

###### Tasks

- [X] Task 1 – Set up Django messages framework to use flash messages for user notification
- [X] Task 2 – Add messages of type Success, Info, Warning and Error for the results of all the user operations
- [X] Task 3 – Create a Shopping Cart template for all the messages related to the shopping Cart
- [X] Task 4 – Modify the Base template to Incorporate Bootstrap-Toasts to the Django message system
