### ISSUE TITLE
USER STORY: Create DIY project details

### ISSUE THREAD

**Issue by Juanma1313** [Juanma1313/diyshop#6]
As **Registered User**, I can **create the DIY project details**, so that **project can have a featured image and description**

###### Acceptance Criteria

- Acceptance Criteria 1
**Given** that I am a `Registered User` 
**When** I have created a new DIY Project (`Thing`)
**Then** I can assign a Title, Status, and Featured Image

- Acceptance Criteria 2
**Given** that I am a `Registered User` 
**When** I have created a new DIY Project (`Thing`)
**Then** I can edit a WSWG document to the description

- Acceptance Criteria 3
**Given** that I am a `Registered User`
**When** I have created a new DIY Project (`Thing`)
**Then** I need to use a Save button to permanently store the changes in the database

###### Tasks

- [X] Task 1 - Install Django Summernote extension for adding  embedded WSWG editing functionality.
- [X] Task 2 - Create the products/forms.ProductForm to accommodate all detail fields for the new `Thing`
- [X] Task 3 - Create the add_product template to accommodate the new ProductForm
