### ISSUE TITLE
USER STORY: Create Instructions

### ISSUE THREAD

**Issue by Juanma1313** [Juanma1313/diyshop#7]
As **Registered User**, I can **create project instructions for my DIY Projects**, so that **the users can read and follow them**

###### Acceptance Criteria

- Acceptance Criteria 1
**Given** that I am a `Registered User` 
**When** I am in any website page
**Then** I can access the `Add Instructions` option in the user menu 

- Acceptance Criteria 2
**Given** that I am a `Registered User` 
**When** I click on the `Add Instructions` option in the user menu 
**Then** I can create a new `Instructions` element

- Acceptance Criteria 3
**Given** that I am a `Registered User` 
**When** I have created a new `Instructions` element
**Then** I must assign the `Instructions` element to one of my existing DIY Projects

###### Tasks

- [ ] Task 1 - Allow the `Add Instructions` option in the user menu in the base template for the main website
- [ ] Task 2 - create a product/views.add_instructions to allow the creation of new `Instructions` element for registered users
- [ ] Task 3 - create the product/forms.ProductInstructions form to accommodate the Instructions data including Summernote edit functionality to the  `instructions` field to allow for the WSWG edit features.
- [ ] Task 4 - create the product add_instructions template to accommodate the product/forms.ProductInstructions form to present the page to the user.
